Fix ContentEntityGeometryNormalizer support check #1064
The bug was triggered as follows:

I installed/enabled the
[webhooks](https://www.drupal.org/project/webhooks) module.

I created a new outgoing webhook, defined for Asset
create/update/delete events.

I edited an Animal Asset, which did not have intrinsic geometry.
Clicking save caused a server error; message was:

    TypeError: strpos(): Argument #1 ($haystack) must be of type string, null given in strpos()
    (line 101 of /opt/drupal/web/profiles/farm/modules/core/geo/src/Normalizer/ContentEntityGeometryNormalizer.php).

Per @mstenta the logic did not expect `$format` to be NULL, but it was
in this context.

This also replaces `strpos()` with `str_starts_with()` since we
already require PHP 8.