Override the entity_field.manager service class instead of decorating it.
Decorating it was causing the following test failure:

1) Drupal\Tests\farm_entity\Functional\FarmEntityBundleFieldTest::testAll
TypeError: Drupal\Component\DependencyInjection\ReverseContainer::generateServiceIdHash(): Argument #1 ($object) must be of type object, null given